version: '3.1'

services:
  
  redis:
    image: redis:5  
    expose:
      - "6379"
    networks:
      comm:
        aliases:
          - redis_db
  
  node:
    image: node:12
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - REDISIP=redis_db
      - PORT=8080 
    volumes:
      - ./diamondsCluster:/home/node/app
    ports:
      - "8001:8080"
    command: npm start
    networks:
      - comm

networks:
  comm:
