version: '3.1'

services:

  redis:
    image: redis:5  
    ports:
      - 6379:6379

  node:
    image: node:12
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - REDISIP=diamonds_elo_redis_1
      - PORT=8080 
      # - WORKERS=2
    volumes:
      - ./diamondsCluster:/home/node/app
    ports:
      - 8080:8080
    command: "npm start"