version: '3.1'

services:
  
  redis:
    image: redis:5  
    expose:
      - "6379"
    networks:
      comm:
        aliases:
          - redis_db
  
  node:
    image: node:12
    working_dir: /home/node
    environment:
      - NODE_ENV=production
      - REDISIP=redis_db
      - PORT=8080 
    volumes:
      - ./diamondsCluster:/home/node
    ports:
      - "8001:8080"
    command: sh -c "
        npm install
        && npm run corpus-prep 
        && npm start
      "
    user: "node"
    networks:
      - comm

networks:
  comm:
